{
 "title": "GoogleBigTable",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "BIGDATA_CPU",
   "type": "graph",
   "description": "CPU Utilization",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [ "resource.label.instance" ],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/cpu_load",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "delphi-stage",
      "unit": "1",
      "valueType": "DOUBLE"
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "projectName": "delphi-stage",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     }
    }
   ]
  },
  {
   "title": "BIGDATA_ROWSREAD",
   "type": "graph",
   "description": "Rows read",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [ "resource.label.instance" ],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/returned_rows_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "delphi-stage",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "BIGDATA_NODE",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [ "resource.label.instance" ],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/node_count",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "delphi-stage",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}